BEGIN;

-- Behavioral triggers detected from the run stream (proactive push lane).
-- Detect+persist ALL five trigger types; the daemon acts only on wheel_spin in v1.
CREATE TABLE IF NOT EXISTS event_logs.agent_triggers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    session_id UUID NOT NULL,
    trigger_type TEXT NOT NULL,
    run_index INTEGER NOT NULL,
    detail_json JSONB,
    fired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    acted BOOLEAN NOT NULL DEFAULT FALSE,
    response_id UUID,
    -- Dedupe key: a given trigger at a given run for a student/session fires once.
    UNIQUE (student_id, session_id, trigger_type, run_index)
);

CREATE INDEX IF NOT EXISTS idx_agent_triggers_student_fired_at
    ON event_logs.agent_triggers (student_id, fired_at);

-- Distinguish student-prompted (reactive) from proactively-pushed assistant messages,
-- both for research analysis and for the SSE poll to filter on.
ALTER TABLE chat.messages
    ADD COLUMN IF NOT EXISTS origin TEXT NOT NULL DEFAULT 'reactive';

-- The SSE stream polls for new proactive rows per student.
CREATE INDEX IF NOT EXISTS idx_messages_origin_student_created_at
    ON chat.messages (origin, student_id, created_at);

COMMIT;
