-- 009_switch_events.sql
-- Identity-switch detection (ported from lm-dashboard's switch_event table +
-- app/pipeline/switches.py). Records when a studentID arrives in a new casing
-- (cobra3 -> Cobra3) or a new classCode, so the agent can treat them as one
-- student across the switch and researchers can see the event.
BEGIN;

CREATE TABLE IF NOT EXISTS event_logs.switch_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    session_id UUID NOT NULL,
    switch_kind TEXT NOT NULL CHECK (switch_kind IN ('casing', 'class')),
    from_value TEXT,
    to_value TEXT,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_switch_events_student
    ON event_logs.switch_events (student_id, detected_at DESC);

COMMIT;
